### PR TITLE
PR for To do List :Add/Remove feature

### PR DESCRIPTION
**Pull request by ngalamac**
In this project, the following features were added:
- Remove all hardcoded items from the tasks array.
- Create a new JavaScript file for the new functionality.
- Implement a function for adding a new task (add a new element to the array).
- Implement a function for deleting a task (remove an element from the array).
- Implement the edit item feature( this is seen by simply clicking on the list item to edit)
- Add local storage feature

### CODE REVIEW

**Review by Olamarx — CHANGES_REQUESTED** [review]
Hi @ngalamac, 

Good job so far, indeed you have spent time on this project!
There are some issues that you still need to work on to go to the next project but you are almost there!


## Highlights
- Add and remove ✔️
- Readme file professional ✔️

## Required Changes ♻️
_Check the comments under the review._
- [ ] While most of the functions are in place, your tasks are not saved to localStorage so some of the requirements like index, edit are not verifiable, I will encourage you to fix that up.
- [ ] I could not also find some methods like the edit method, kindly add it too.
## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Comment by ngalamac** [comment]
> Hi @ngalamac,
> 
> Good job so far, indeed you have spent time on this project! There are some issues that you still need to work on to go to the next project but you are almost there!  [ 68747470733a2f2f6d65646961312e67697068792e636f6d2f6d656469612f74385950663341434b656f754c7a454976722f67697068792e676966 ](https://camo.githubusercontent.com/957cdd5c6c73009f305aa460cba68fe9b38c4cf1eead69c6006a391516168166/68747470733a2f2f6d65646961312e67697068792e636f6d2f6d656469612f74385950663341434b656f754c7a454976722f67697068792e676966) [ ](https://camo.githubusercontent.com/957cdd5c6c73009f305aa460cba68fe9b38c4cf1eead69c6006a391516168166/68747470733a2f2f6d65646961312e67697068792e636f6d2f6d656469612f74385950663341434b656f754c7a454976722f67697068792e676966)
> 
> ## Highlights
> * Add and remove ✔️
> * Readme file professional ✔️
> 
> ## Required Changes ♻️
> _Check the comments under the review._
> 
> * [ ]  While most of the functions are in place, your tasks are not saved to localStorage so some of the requirements like index, edit are not verifiable, I will encourage you to fix that up.
> * [ ]  I could not also find some methods like the edit method, kindly add it too.
> 
> ## Optional suggestions
> _Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._
> 
> Cheers and Happy coding!👏👏👏
> 
> Feel free to leave any questions or comments in the PR thread if something is not 100% clear. Please, remember to tag me in your question so I can receive the notification.
> 
> **_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**
> 
> _As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you t

**Comment by ngalamac** [comment]
Hello sir, thank you for the review
Please I will like to highlight that the edit feature is actually present. Just click on the item and it will become editable . Thank you

**Review by Strangeal — APPROVED** [review]
Hi @ngalamac, 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

Alt Text


## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Pull request closed without merging**
